// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utbvglghiaqninhqtunx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0YnZnbGdoaWFxbmluaHF0dW54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODI1NzAsImV4cCI6MjA3MjQ1ODU3MH0.v_WodYSD060koQ755pF6YhvZpYwGzYGGwXPx2Ksx2jo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});